---
- hosts: all
  tasks:
  - name: set project dependencies to latest
    command: mvn versions:use-latest-versions -DallowSnapshots=true -DexcludeReactor=false -Dincludes=com.wwa.*
    args:
      chdir: "{{path}}"
  - name: update version
    command: mvn -B release:update-versions -DallowSnapshots=true -DautoVersionSubmodules=true
    args:
      chdir: "{{path}}"
  - name: build package
    command: mvn package
    args:
      chdir: "{{path}}"
  - name: get latest package version
    shell: mvn help:evaluate -Dexpression=project.version | grep -v '\['
    register: package_version
    args:
      chdir: "{{path}}"
  - name: run app-example
    command: java -jar target/app-example-{{package_version.stdout}}.jar
    args:
      chdir: "{{path}}"
